// import { Inter } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "My Portfolio",
//   description: "Generated by create next app",
// };
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <header>
//           <nav>
//             <Link href="/welcome">welcome</Link>
//             <Link href="/home">home</Link>
//             <Link href="/about">about</Link>
//             <Link href="/projects">projects</Link>
//             <Link href="/contact">contacts</Link>
//           </nav>
//         </header>
//         {children}
//         <footer className="text-center">&copy; My Portfolio</footer>
//         </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Portfolio",
  description:
    "Projects created by Tiffany.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-100">
          <nav className="flex justify-center w-100 ">
            <Link
              className="m-1 text-emerald-500 hover:text-emerald-700"
              href="/"
            >
              Home
            </Link>
            <Link
              className="m-1 text-emerald-500 hover:text-emerald-700"
              href="/management"
            >
              Manage Library
            </Link>
            <Link
              className="m-1 text-emerald-500 hover:text-emerald-700"
              href="/about"
            >
              About
            </Link>
          </nav>
        </header>
        {children}
        <footer className="text-center">&copy; Codex January Cohort</footer>
      </body>
    </html>
  );
}