import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <Link href="/">welcome</Link>
            <Link href="/">home</Link>
            <Link href="/about">about</Link>
            <Link href="/projects">projects</Link>
            <Link href="/contact">contacts</Link>
          </nav>
        </header>
        {children}
        <footer></footer>
        </body>
    </html>
  );
}